# .github/workflows/version-check.yml
name: Version Check and Trigger Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# 权限变更：不再需要写仓库，只需要触发其他 action
permissions:
  contents: read
  actions: write

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      needs-version-bump: ${{ steps.version-check.outputs.needs-bump }}
      new-version: ${{ steps.version-check.outputs.new-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Get current version from package.json
        id: current-version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "current-version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $CURRENT_VERSION"

      - name: Get latest tag version
        id: latest-tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//' || echo "0.0.0")
          echo "latest-tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "Latest tag version: $LATEST_TAG"

      - name: Check if version bump is needed
        id: version-check
        # ... 此处逻辑与您原来的一样，保持不变 ...
        run: |
          CURRENT="${{ steps.current-version.outputs.current-version }}"
          LATEST_TAG="${{ steps.latest-tag.outputs.latest-tag }}"

          echo "Comparing versions: Current=$CURRENT, Latest Tag=$LATEST_TAG"

          if [ "$CURRENT" = "$LATEST_TAG" ]; then
            echo "Version $CURRENT is same as latest tag, incrementing patch version..."
            IFS='.' read -r -a version_parts <<< "$CURRENT"
            major=${version_parts[0]}
            minor=${version_parts[1]}
            patch=${version_parts[2]}
            new_patch=$((patch + 1))
            NEW_VERSION="$major.$minor.$new_patch"
            echo "needs-bump=true" >> $GITHUB_OUTPUT
            echo "new-version=$NEW_VERSION" >> $GITHUB_OUTPUT
            echo "New version will be: $NEW_VERSION"
          else
            echo "Version $CURRENT is different from latest tag $LATEST_TAG, no bump needed"
            echo "needs-bump=false" >> $GITHUB_OUTPUT
            echo "new-version=$CURRENT" >> $GITHUB_OUTPUT
          fi

  # 这个 job 完全被替换了
  trigger-publish-event:
    needs: check-version
    if: needs.check-version.outputs.needs-version-bump == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Publish Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-publish # 定义我们的事件名
          client-payload: '{"version": "${{ needs.check-version.outputs.new-version }}"}'